### ISSUE TITLE
Allow (optional) process arguments to specify which column(s) to process the cut on

### ISSUE THREAD

**Issue by adambrown1** [XENON1T/lax#13]
For example, at the moment it is not possible to use the width cut on a second S2. But if the user could choose the 's2' and 's2_range_50p_area' column names it would be easy to do this.

**Comment by tunnell** [comment]
Make this class variable:

https://github.com/XENON1T/lax/blob/master/lax/lichens/sciencerun0.py#L224

Then allow people to overload at init()?

**Comment by adambrown1** [comment]
I think to implement this and keep the existing ManyLichen structure will mean passing the class variables from the outer class to the inners through init() and then back out to the parent function subpre which seems messy to me - the other option is to refactor and put everything in one single S2 cut class which checks both limits and has no inner classes. Any comment?

**Comment by JelleAalbers** [comment]
Since this is over two years old, I'm closing this issue. Feel free to reopen if there is interest.
