### ISSUE TITLE
S2 width depends on drift time, not depth

### ISSUE THREAD

**Issue by tunnell** [XENON1T/lax#133]
The 'z' parameter is corrected depth:

https://github.com/XENON1T/hax/blob/master/hax/treemakers/corrections.py#L35

The width cut is defined on this corrected z. Diffusion depends on drift time.  This was caught by @rafaellang.

**Comment by tunnell** [comment]
Use from Basics the drift_time variable.

**Comment by zhut19** [comment]
I do realize using drift time is the correct definition, but drift time don't reflect the ~2us that electron took to drift from gate to liquid level, which would have a different diffusion model. (However, z already subtracted this part)

**Comment by rafaellang** [comment]
How about adding those 2us to drift time as a constant offset?

**Comment by pdeperio** [comment]
Fixed in #134
