### ISSUE TITLE
S2-dependent acceptance of S2PatternLikelihood cut

### ISSUE THREAD

**Issue by JosephJHowlett** [XENON1T/lax#148]
In investigating cuts while preparing to extend the fitting of Rn220 data to higher energy for post-SR1 analyses, it seemed that the S2Pattern cut had the dominating acceptance drop at higher E:

![nm1_first_10_cuts_rn220_sr1_180515](https://user-images.githubusercontent.com/16269427/40125468-024675ec-58f9-11e8-98d5-8777dc688a1e.png)

This can be seen as well in S2 (the space in which [Tianyu tuned the cut](https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenon1t:sim:notes:tzhu:pattern_cut_tuning):

![current_s2patternlikelihood_s2](https://user-images.githubusercontent.com/16269427/40125545-304d3908-58f9-11e8-8e7b-6de37e5155c1.png)

Fortunately Tianyu had a re-tuned version of the cut ready, which already solves the problem:

![new_s2patternlikelihood_s2](https://user-images.githubusercontent.com/16269427/40125613-5239ebc4-58f9-11e8-91a4-399c65836696.png)

This should be PR'ed for use in post-SR1 analyses (particularly higher-energy).

**Comment by JelleAalbers** [comment]
I think this has been addressed by Jingqiang in #153: anyone using the postsr1 lichen file will get his updated cut automatically now. @jhowl01 if you agree, can you close?

**Comment by JosephJHowlett** [comment]
Yes looks great, thanks for the ping!
