### ISSUE TITLE
Need DAQ, "self-veto", or junk cut

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/lax#35]
From [the waveform watching campaign](https://xecluster.lngs.infn.it/dokuwiki/doku.php?id=xenon:xenon1t:analysis:firstresults:waveform_watching), many events in calibration data difficult to classify due to messy waveforms (e.g. after HE event). One example below as well as event lists of categories ```4b``` and others with comments ```pile-up``` on [the waveform watching spreadsheet](https://docs.google.com/spreadsheets/d/1vggMO1r7Ev8SOuYG3VYIHNLdIzGym7vo5kBWQjBM_yY/edit?ts=58a4cd8f#gid=878005143).

Of course, probably can't be applied to calibration data directly, but can check with the [upcoming time-difference cut](https://xecluster.lngs.infn.it/dokuwiki/doku.php?id=xenon:xenon1t:analysis:self_veto_sr0) and close this after implementation.

![cat4b_161022_0417_13874](https://cloud.githubusercontent.com/assets/8642192/23681998/1ea928d6-0357-11e7-9486-3e4ca43b460e.png)

**Comment by coderdj** [comment]
DAQ cut requires updated hax and remaking proximity minitrees. 

Self-veto cut is going to require a set of new minitrees with a new variable. 

I can put whatever cuts in lax but it will crash everyone's analysis until minitrees there.

**Comment by coderdj** [comment]
Pull request #39
