### ISSUE TITLE
Potential multiple-scatters that may be removed by S2 GOF cut

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/lax#36]
From [the waveform watching campaign](https://xecluster.lngs.infn.it/dokuwiki/doku.php?id=xenon:xenon1t:analysis:firstresults:waveform_watching), ~1% S2s have some multi-peak structure indicative of a multiple-scatter or multi-SE. Example below as well as event lists of categories ```2d, 4g``` on [the waveform watching spreadsheet](https://docs.google.com/spreadsheets/d/1vggMO1r7Ev8SOuYG3VYIHNLdIzGym7vo5kBWQjBM_yY/edit?ts=58a4cd8f#gid=878005143).

These may be identified by the upcoming S2 pattern likelihood cut (https://github.com/XENON1T/lax/pull/34), to be checked and this issue closed if confirmed.

![cat2d_161227_0030_121786](https://cloud.githubusercontent.com/assets/8642192/23682152/fa938dfa-0357-11e7-8152-0fa0266bd274.png)

**Comment by tunnell** [comment]
@pelssers

**Comment by pelssers** [comment]
This particular event would not be cut by the current version of the s2 patternfit cut.
The cut value is 614.4 = 10*(s2=7059**0.45) + 75
The gof = 555.6 which is lower and thus passes the cut

Details of the cut can be found here:
https://xecluster.lngs.infn.it/dokuwiki/doku.php?id=xenon:xenon1t:analysis:firstresults:s2_pattern_likelihood_cut

Making the cut less conservative may of course remove these events and needs to be investigated for SR1

**Comment by pdeperio** [comment]
Please leave comment when closing, like: ```S2PatternLikelihood``` has been retuned in https://github.com/XENON1T/lax/pull/87, and shouldn't be fine-tuned on single events that lie near boundary like these
