### ISSUE TITLE
Warning in single electron cut

### ISSUE THREAD

**Issue by JelleAalbers** [XENON1T/lax#48]
```
/home/aalbers/lax/lax/lichens/sciencerun0.py:673: FutureWarning: in the future, boolean array-likes will be handled as a boolean array index
  passes[cond] = df[self.rt_variable][cond] < SingleElectronS2s.bound_v4(df[self.aft_variable][cond])
```
Probably `cond = cond.values` or something will help. Not sure if this means there is a problem (cond will be treated as boolean array index in the future, but what is it being treated as now?)

**Comment by tunnell** [comment]
Fixed in #51.  Reopen if not.
