### ISSUE TITLE
Lax should output which minitree is missing if it is missing a variable

### ISSUE THREAD

**Issue by sanderbreur** [XENON1T/lax#6]
Right now it would give the error: 
AttributeError: 'DataFrame' object has no attribute 'area_before_main_s2'

But that doesn't tell the person who runs it how to solve it.

**Comment by JelleAalbers** [comment]
Ideally each lichen would have some attribute saying which minitrees it requires. The next step would be adding a function that loads all required minitrees I guess.

**Comment by tunnell** [comment]
Won't fix for moment.  Feel free to add.  Will do once this settles more.
