### ISSUE TITLE
Need run dependence?

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/lax#61]
@jpienaar13 discovered that the drift velocity in the [S2Width cut](https://github.com/XENON1T/lax/blob/v0.11.1/lax/lichens/sciencerun0.py#L581) is being grabbed from the [static pax config file](https://github.com/XENON1T/pax/blob/master/pax/config/XENON1T.ini#L416) (1.440 * um / ns), which would be incorrect for [SR1](https://github.com/XENON1T/lax/pull/59) (1.333 * um / ns).  Should we just hardcode these numbers in the respective lichens?

Not sure how many other run dependent quantities are being used, and how you want to deal with this in general (pulling from DB seems like bloat, though also the new MC/data reduction program is [suffering from this](https://github.com/XENON1T/lax/blob/master/bin/laxer#L60)).

**Comment by coderdj** [comment]
I would just hardcode. Or, smarter, put any run-dependent constants as member variables of the lichen. Then if the cut remains the same (except constants) in the next run you can just override the constants in the new sciencerun_x.py.

**Comment by tunnell** [comment]
I agree, hardcode.  Inherit from SR0 lichen, then overload just that one value.

**Comment by pdeperio** [comment]
@weiyuehuan hardcoded (https://github.com/XENON1T/lax/pull/62/commits/45e53251c52e3b8e1893f4b779b885d11280526e)
