### ISSUE TITLE
Remove SingleElectronS2s from SR0 too?

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/lax#68]
Should the ```SingleElectronS2s``` cut be removed from SR0 too [here](https://github.com/XENON1T/lax/blob/v1.0.0/lax/lichens/sciencerun0.py#L72) (triggered by https://github.com/XENON1T/pax/pull/576)?

**Comment by MAVJ** [comment]
I would think that for SR0 or SR1, if the pax version of the processed data is not at least pax.6.6.6 or something newer, then the cut may be needed, given that for pax 6.6.6 on the cut it is already on pax classification.
