### ISSUE TITLE
Need InteractionPeaksBiggest with pax twostepgap clustering

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/lax#70]
If the new pax ```TwoStepGap``` clustering is merged (https://github.com/XENON1T/pax/pull/596) as is, will need to reinstate the ```InteractionPeaksBiggest``` cut in [sciencrun1.py](https://github.com/XENON1T/lax/blob/master/lax/lichens/sciencerun1.py) (to reject e.g. Figure 8b in [this note](https://xecluster.lngs.infn.it/dokuwiki/doku.php?id=xenon:xenon1t:analysis:sciencerun1:headless_detector#update_17_07_27)).

**Comment by feigaodm** [comment]
Also needed for accidental coincidence background analysis. Otherwise there will be mis-modelled background in Rn220 calibration data
