### ISSUE TITLE
Tune or remove S1 AFT cut at high energy

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/lax#79]
Following discussion in https://github.com/XENON1T/pax/issues/609, S1 AFT cut should be tuned or removed at high energy to avoid loss of efficiency as shown in [Fig. 6 here](https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenon1t:darryl:s1_aft_update#cut_performance_using_fax) and [Fig. 4.2 here](https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenon1t:analysis:sciencerun1:g1_g2_systematics#effect_of_different_cut_sets).

**Comment by pdeperio** [comment]
Is this still an issue?

**Comment by darrylmasson** [comment]
![s1_aft_pvalue_vs_s1](https://user-images.githubusercontent.com/10812861/31826867-3bd3742c-b584-11e7-9528-bad5973f7089.png)
The values aren't p-value distributed above a few hundred PE, so the cut loses its power. I'll try to get a PR in on Monday or Tuesday to remove this cut from the all-energy lichens.
Ninja edit: that's log-10 on both axes.
