### ISSUE TITLE
Double S1 Mis-ID Cut

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/lax#82]
Request by @skazama to tighten the ```S2SingleScatter``` (and ```S2SingleScatterSimple```) cut at high energy to reduce the Kr83m contamination in background data, as shown [here](https://xe1t-wiki.lngs.infn.it/lib/exe/detail.php?id=xenon%3Akazama%3Aambe_ng_comparison%3Aperformance_check_ng_ambe&media=xenon:kazama:ambe_ng_comparison:cut_largest_other_s2_vs_s2_rn220_bg.png).  ([Original tuning note](https://xecluster.lngs.infn.it/dokuwiki/doku.php?id=xenon:xenon1t:analysis:firstresults:cut:s2single) looks like only up to 5000 pe.)

Also a suggestion by @andrewgrahambrown to tighten at low energy too.

Edit: This should be a new cut against mis-IDed double S1s instead of tightening ```S2SingleScatter```.

**Comment by pdeperio** [comment]
@zhut19 found these are S1s mis-ID'ed as S2, occurring very near the main S1. He added some more variables in https://github.com/XENON1T/hax/pull/157 to help reject this population. @zhut19 please post details when you have a result.

**Comment by skazama** [comment]
Yes, in this case s1[0] (main s1) is from 9keV and 32 keV s1 is mis-identifed as s2[1] as I presented in the cut meeting. You can see those waveforms here. https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:kazama:ambe_ng_comparison:performance_check_ng_ambe#appendix_a1_waveforms_for_kr83m_contamination

**Comment by skazama** [comment]
From the waveforms shown in the above link, it seems that there are overlap between s1[0] and s2[1]. This behavior is understood from clustering point of view? Also I'm not sure why 32 keV s1 is reconstructed as s2. I hope @zhut19 or someone can investigate the details.

**Comment by coderdj** [comment]
This was handled by #103
