### ISSUE TITLE
S1 area_fraction_top

### ISSUE THREAD

**Issue by feigaodm** [XENON1T/lax#91]
When I tried to apply S1 AFT cut to simulated AC data, I met the following error. I don't know if it's due to some bug in LAX. I remember @darrylmasson changes sth in pax, not sure if LAX should be changed too. 

'''''''''''''''''''''''''''''''''''''''
----> 2 df_ac_model = cuta.process(df_ac_model)

/project/lgrandi/anaconda3/envs/pax_head/lib/python3.4/site-packages/lax-1.0.0-py3.4.egg/lax/lichen.py in process(self, df)
     26 
     27     def process(self, df):
---> 28         df = self.pre(df)
     29         df = self._process(df)
     30         df = self.post(df)

/project/lgrandi/anaconda3/envs/pax_head/lib/python3.4/site-packages/lax-1.0.0-py3.4.egg/lax/lichens/sciencerun0.py in pre(self, df)
    684                                                                        self.aft_map(np.sqrt(row['x']**2 + row['y']**2),
    685                                                                                     row['z'])[0, 0]),
--> 686                                                 axis=1)
    687         return df
    688 

/project/lgrandi/anaconda3/envs/pax_head/lib/python3.4/site-packages/pandas/core/frame.py in apply(self, func, axis, broadcast, raw, reduce, args, **kwds)
   4059                     if reduce is None:
   4060                         reduce = True
-> 4061                     return self._apply_standard(f, axis, reduce=reduce)
   4062             else:
   4063                 return self._apply_broadcast(f, axis)

/project/lgrandi/anaconda3/envs/pax_head/lib/python3.4/site-packages/pandas/core/frame.py in _apply_standard(self, func, axis, ignore_failures, reduce)
   4155             try:
   4156                 for i, v in enumerate(series_gen):
-> 4157                     results[i] = func(v)
   4158                     keys.append(v.name)
   4159             except Exception as e:

/project/lgrandi/anaconda3/envs/pax_head/lib/python3.4/site-packages/lax-1.0.0-py3.4.egg/lax/lichens/sciencerun0.py in <lambda>(row)
    683                                                                        np.round(row['s1']),
    684                                                                        self.aft_map(np.sqrt(row['x']**2 + row['y']**2),
--> 685                                                                                     row['z'])[0, 0]),
    686                                                 axis=1)
    687         return df

/project/lgrandi/anaconda3/envs/pax_head/lib/python3.4/site-packages/scipy/stats/morestats.py in binom_test(x, n, p, alternative)
   2025         x = x[0]
   2026         if n is None or n < x:
-> 2027             raise ValueError("n must be >= x")
   2028         n = np.int_(n)
   2029     else:

ValueError: ('n must be >= x', 'occurred at index 1892')
'''''''''''''''''''''''

**Comment by darrylmasson** [comment]
A few things:
a) The function call that fails is scipy.stats.binom_test, and it's failing because the data you're giving it has s1_top > s1. Any idea why this is happening?
b) This call is only made in legacy code using the very old (r,z) map that only exists for compatibility with old versions of pax, which means you're using an old version of pax, you're loading an old version of the Extended minitree, or there's a typo somewhere. What versions are you using here?

**Comment by feigaodm** [comment]
Thanks, case a) is the problem I met and I fixed it by trancating the S1_AFT range. Now it works.

I'm testing the effect on this cut on AC predictions so it's applied on simulated branches, so no specific minitrees are needed. 

The only problem I have now is this is too slow and I have to parallize the calculation.
