### ISSUE TITLE
Naming of cut classes: LowEnergyBackground

### ISSUE THREAD

**Issue by tunnell** [XENON1T/lax#95]
In #86 various things were removed and I think that created some confusions.

First, there is LowEnergyBackground and LowEnergyRn220, so what do people use?  LowEnergyBackground contains a junk cut that we don't want on AmBe or DD, right?  

Nevertheless, it should always be clear to the analyst which to use so maybe for now rename LowEnergyBackground to LowEnergy?

Also, the fiducial volume cut can be simplified so it's not redefined.  Move source position to the class.  Then in SR1 do:

`FiducialVolume = sr0.FiducialVolume
FiducialVolume.position = blah`

**Comment by pdeperio** [comment]
Should be fixed in last two PRs above
